# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# lintr provides static code analysis for R.
# It checks for adherence to a given style,
# identifying syntax errors and possible semantic issues,
# then reports them to you so you can take action.
# More details at https://lintr.r-lib.org/

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '23 5 * * 3'

name: lintr

permissions:
  actions: write
  contents: read
  packages: write
  pull-requests: write
  security-events: write

jobs:
  lint:
    uses: dfe-analytical-services/dfeshiny/.github/workflows/lintr_reusable.yaml@fix/lintr-load-all-same-session
    with:
      is_package: "true"
